// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calendar_roundtrip_date
Rcpp::DateVector calendar_roundtrip_date(Rcpp::DateVector x);
RcppExport SEXP _calendarrr2_calendar_roundtrip_date(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::DateVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(calendar_roundtrip_date(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_calendarrr2_calendar_roundtrip_date", (DL_FUNC) &_calendarrr2_calendar_roundtrip_date, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_calendarrr2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
