# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calendar_adjust <- function(x, convention, calendar) {
    .Call(`_almanac_calendar_adjust`, x, convention, calendar)
}

calendar_adjust_end_of_month <- function(x, calendar) {
    .Call(`_almanac_calendar_adjust_end_of_month`, x, calendar)
}

calendar_shift <- function(x, by, unit, convention, end_of_month, calendar) {
    .Call(`_almanac_calendar_shift`, x, by, unit, convention, end_of_month, calendar)
}

calendar_count_business_days_between <- function(starts, stops, calendar) {
    .Call(`_almanac_calendar_count_business_days_between`, starts, stops, calendar)
}

calendar_is_weekend <- function(x, calendar) {
    .Call(`_almanac_calendar_is_weekend`, x, calendar)
}

calendar_is_business_day <- function(x, calendar) {
    .Call(`_almanac_calendar_is_business_day`, x, calendar)
}

calendar_is_holiday <- function(x, calendar) {
    .Call(`_almanac_calendar_is_holiday`, x, calendar)
}

calendar_is_end_of_month <- function(x, calendar) {
    .Call(`_almanac_calendar_is_end_of_month`, x, calendar)
}

calendar_holidays_between <- function(start, stop, weekends, calendar) {
    .Call(`_almanac_calendar_holidays_between`, start, stop, weekends, calendar)
}

calendar_seq <- function(start, stop, by, unit, start_convention, stop_convention, end_of_month, calendar) {
    .Call(`_almanac_calendar_seq`, start, stop, by, unit, start_convention, stop_convention, end_of_month, calendar)
}

